name: 'Check go func complexities with reviewdog'
description: 'Measure and report complexities of functions with reviewdog'
author: 'shoooooman'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
    default: ${{ github.token }}
  cycloover:
    description: 'show functions with the Cyclomatic complexity > N (default: 10)'
    required: false
    default: 10
  maintunder:
    description: 'show functions with the Maintainability index < N (default: 20)'
    required: false
    default: 20

runs:
  using: 'composite'
  steps:
    - run: go get github.com/shoooooman/go-complexity-analysis/cmd/complexity
      shell: bash
    - run: ${{ github.action_path }}/install.sh
      shell: bash
    - run: reviewdog -reporter=github-pr-review -level=info
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github_token }}
      shell: bash
